### ISSUE TITLE
What is inside set-of-emails/jsonobj directory?

### ISSUE THREAD

**Issue by kapitonas** [sisimai/rb-Sisimai#141]
Hi, Guys. 

I have a little issue. Trying to find the full samples for what sisimai generates when some server output is pushed to it. For example I see there *.eml file with such content:
```
The original message was received at Wed, 16 Oct 2013 14:15:34 +0900
from p0000-ipbfpfx00kyoto.kyoto.example.co.jp [192.0.2.25]

   ----- The following addresses had permanent fatal errors -----
<userunknown@bouncehammer.jp>
    (reason: 550 5.1.1 <userunknown@bouncehammer.jp>... User Unknown)

   ----- Transcript of session follows -----
... while talking to mx.bouncehammer.jp.:
>>> DATA
<<< 550 5.1.1 <userunknown@bouncehammer.jp>... User Unknown
550 5.1.1 <userunknown@bouncehammer.jp>... User unknown
<<< 503 5.0.0 Need RCPT (recipient)
```
Where is the sample for JSON generated from sisimai. I expect that ```"reason":"userunknown"``` should be generated at one of JSON object, but when I look at all JSON objects inside ```/set-of-emails```, there is no such sample.
Content of ```/set-of-emails/jsonobj``` there are many ```JSON``` objects. My gues was that it's  ```output``` of ```sisimai``` when ```input``` was some server responses. I was expecting that this is true. After investigation I'm not so sure any more.
This content is sort of helpful, but something is wrong with it's arrangement and structuring it. It's not clear for me if it's actual sisimai responses or just a intermediate JSON object used for tests of other purposes for application. 
Some questions that I could not find the answer my self:

1. What is the reason naming files like ```json-sendgrid-03.json```? I cold not find eny email data called ````json-sendgrid-03.eml```, but I was hoping I would :)
2. For what email response (file with *.eml) is content in ```json-sendgrid-03.json``` is ```output```?
3. Why content of files in ```json-amazonses-*.json``` is so very different from ```json-sendgrid-*.json``` files content. And why content of ```json-sendgrid-*.json``` is much shorter than content in ```json-amazonses-*.json```.
4. If content of ```set-of-emails``` have examples sisimai responses, why there are not all types of responses. For example I could not find JSON with "softbounce" atribute. On web site there is example ```https://libsisimai.org/en/start/#usage``` named ```JSON string filtered by jq utility```. Looking at every instance of JSON in directory, I could not find anything similar to what is provided int example. This is why I'm asking what is the purpose of all those ```.json``` files.

Sorry, for so many questions, but I think there is a space for improvements that would make this application even better.

p.s. I was struggling to install it because had no experineced with Ruby or RVM, but with helps looks like it works. 

p.s.s. Maybe there is the documentation, description of what is the structure directories, but I could not find it yet.

**Comment by azumakuniyuki** [comment]
Hello, @kapitonas,

Thanks for questions. First of all, `set-of-emails` directory exists for only `make test` by sisimai developers.

> 1. What is the reason naming files like json-sendgrid-03.json? I cold not find eny email data called ````json-sendgrid-03.eml```, but I was hoping I would :)

Each file which name ends with `.json` in `set-of-emails/jsonobj` is JSON text, is not an email.
The Content of these sample JSON text files is a response from an email cloud such as SendGrid, Amazon SES.
We use `*.eml` file extension for an email text only.


> 2. For what email response (file with *.eml) is content in json-sendgrid-03.json is output?

`json-sendgrid-*.json` are not an output from sisimai, are raw response from SendGrid API described at [Event Webhook Reference](https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html) or [Bounces API](https://sendgrid.com/docs/API_Reference/Web_API_v3/bounces.html).

> 3. Why content of files in json-amazonses-*.json is so very different from json-sendgrid-*.json files content. And why content of json-sendgrid-*.json is much shorter than content in json-amazonses-*.json.

`json-amazonses-*.json` are raw response from Amazon SES described at [Bounce Ojbect](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#bounce-object).

> 4. If content of set-of-emails have examples sisimai responses, why there are not all types of responses. For example I could not find JSON with "softbounce" atribute. On web site there is example https://libsisimai.org/en/start/#usage named JSON string filtered by jq utility. Looking at every instance of JSON in directory, I could not find anything similar to what is provided int example. This is why I'm asking what is the purpose of all those .json files.

There is no sample JSON text generated by sisimai in neither `set-of-emails` directory nor other directories.
The sample JSON text generated from sisimai is in the bottom of https://libsisimai.org/en/start/.

> p.s.s. Maybe there is the documentation, description of what is the structure directories, but I could not find it yet.

Description about directory structure of `set-of-emails` is https://github.com/sisimai/p5-Sisimai/tree/master/set-of-emails only.

Best regards :-)
