### ISSUE TITLE
5.0.2pX on rubygems.org?

### ISSUE THREAD

**Issue by dmke** [sisimai/rb-sisimai#285]
Hi,

```console
$ gem install sisimai
```

will currently install v5.0.2, not 5.0.2p2, nor p3.

Would you publish these versions to Rubygems as well?

It would also be convenient, if you could abstain from the X.Y.ZpP version format and use X.Y.Z.P (Rubygems will mark the former version as pre-release, cf. [semver.org](https://semver.org/)).

**Comment by azumakuniyuki** [comment]
Hello,

Following the policy, releases with `p` in their version numbers will be considered pre-release versions and will not be uploaded to the public package repositories CPAN (The Perl version of Sisimai) and RubyGems. Instead, these packages will only be made available on GitHub for development and testing purposes.

For your convenience, you may use the git clone command if you require the repository immediately.

```
$ git clone https://github.com/sisimai/rb-sisimai.git -b v5.0.2p3
```

And then, we will release v5.0.3 on 22nd May.
https://twitter.com/libsisimai/status/1789911808188248121

**Comment by dmke** [comment]
Ah, I see. Thank you for clarification.

I was under the impression that "p" releases were some kind of hotfix/patch.

(Also N.B.: I don't use Twitter anymore, as it has become utterly unusable.)
