### ISSUE TITLE
Test on Windows with JRuby

### ISSUE THREAD

**Issue by azumakuniyuki** [sisimai/rb-Sisimai#37]
<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr"><a href="https://twitter.com/azumakuniyuki">@azumakuniyuki</a> ご存知かもしれませんが、Windows上のCIは、<a href="https://t.co/OgPCk8QHwb">https://t.co/OgPCk8QHwb</a> これを使っているのが、私のしっているオープンソースのソフトでは多いです。</p>&mdash; hiroyuki sato (@hiroysato) <a href="https://twitter.com/hiroysato/status/694838401745362944">February 3, 2016</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
https://ci.appveyor.com/project/azumakuniyuki/rb-sisimai

**Comment by hiroyuki-sato** [comment]
FYI Configuration example.

* [Embulkl](https://github.com/embulk/embulk/blob/master/appveyor.yml)
* [Groonga](https://github.com/groonga/groonga/blob/master/appveyor.yml)

**Comment by azumakuniyuki** [comment]
@hiroyuki-sato Thanks for the advice about configuration !

**Comment by hiroyuki-sato** [comment]
I found better example.

* [fluentd](https://github.com/fluent/fluentd/blob/master/appveyor.yml)

Because it use ``rake test`` command.

**Comment by azumakuniyuki** [comment]
@hiroyuki-sato Thanks for the sample, I've copied the file into this repository as a test.

**Comment by azumakuniyuki** [comment]
https://ci.appveyor.com/project/azumakuniyuki/rb-sisimai
