### ISSUE TITLE
rb-Sisimai does not work properly in multithread environment.

### ISSUE THREAD

**Issue by hiroyuki-sato** [sisimai/rb-Sisimai#40]
Reference.

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/hiroysato">@hiroysato</a> ここで、クラス変数（マルチスレッドで共有されている）に対して、ロックなしでconcat（配列を破壊的に変更する）しているのがマズそうな気がします：<a href="https://t.co/xE7BZZvOOH">https://t.co/xE7BZZvOOH</a></p>&mdash; Sadayuki Furuhashi (@frsyuki) <a href="https://twitter.com/frsyuki/status/695423359010476032">2016, 2月 5</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

I'm developing [embulk-parser-sisimai_analyzer](https://github.com/hiroyuki-sato/embulk-parser-sisimai_analyzer). It run in multithread environment.

[error log](https://gist.github.com/hiroyuki-sato/6156dfb939fd7dc7da08)

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/hiroysato">@hiroysato</a> ad-hocですが典型的な回避策は、まずクラスに定数 GLOBAL_MUTEX = <a href="https://t.co/Uk7arSpaiP">https://t.co/Uk7arSpaiP</a> を定義しておいて、</p>&mdash; Sadayuki Furuhashi (@frsyuki) <a href="https://twitter.com/frsyuki/status/695423854320099329">2016, 2月 5</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/hiroysato">@hiroysato</a> Sisimai::<a href="https://t.co/x6qwXS0Hrh">https://t.co/x6qwXS0Hrh</a> を、GLOBAL_MUTEX.synchornized { Sisimai::<a href="https://t.co/x6qwXS0Hrh">https://t.co/x6qwXS0Hrh</a> } に置き換える方法があります。まぁそれほど悪くないと思います</p>&mdash; Sadayuki Furuhashi (@frsyuki) <a href="https://twitter.com/frsyuki/status/695424023501516800">2016, 2月 5</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by azumakuniyuki** [comment]
@hiroyuki-sato Thanks for the report. I'll check and try to fix these code at this night or tomorrow.

**Comment by hiroyuki-sato** [comment]
I tried #43. It seems work well. 👍

**Comment by azumakuniyuki** [comment]
@hiroyuki-sato Thank you to immediately test !!!
