### ISSUE TITLE
Sisimai::Mail::STDIN does not work properly

### ISSUE THREAD

**Issue by azumakuniyuki** [sisimai/rb-Sisimai#61]
https://twitter.com/yaegassy/status/770207049808355328

```shell
% cat path/to/mail.eml | ruby -rsisimai -e 'puts Sisimai.dump(STDIN)'
/usr/local/lib/ruby/gems/2.3.0/gems/sisimai-4.17.2/lib/sisimai/mail/stdin.rb:40:in `gets': closed stream (IOError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/sisimai-4.17.2/lib/sisimai/mail/stdin.rb:40:in `read'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sisimai-4.17.2/lib/sisimai/mail.rb:70:in `read'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sisimai-4.17.2/lib/sisimai.rb:33:in `make'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sisimai-4.17.2/lib/sisimai.rb:54:in `dump'
	from -e:1:in `<main>'
```

It does not work properly when the 1st argument of Sisimai.dump() is neither `STDIN` nor `"<STDIN>"`. The following gist is a workaround patch to resolve this bug.
https://gist.github.com/azumakuniyuki/0d903f88201cb605bbc229f928079e4a

**Comment by vodolaz095** [comment]
i had nearly the same issue. sorry, i don't know ruby, so hard to debug it


[vodolaz095@steel sisi]$ cat sample2.eml | ruby -rsisimai -e 'puts Sisimai.dump(<STDIN>)'
Traceback (most recent call last):
	16: from <internal:abrt_prelude>:5:in `<internal:abrt_prelude>'
	15: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
	14: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	13: from /usr/share/rubygems/rubygems.rb:213:in `try_activate'
	12: from /usr/share/rubygems/rubygems/specification.rb:1063:in `find_by_path'
	11: from /usr/share/rubygems/rubygems/specification.rb:850:in `stubs'
	10: from /usr/share/rubygems/rubygems/specification.rb:782:in `installed_stubs'
	 9: from /usr/share/rubygems/rubygems/specification.rb:790:in `map_stubs'
	 8: from /usr/share/rubygems/rubygems/specification.rb:790:in `flat_map'
	 7: from /usr/share/rubygems/rubygems/specification.rb:790:in `each'
	 6: from /usr/share/rubygems/rubygems/specification.rb:793:in `block in map_stubs'
	 5: from /usr/share/rubygems/rubygems/specification.rb:768:in `gemspec_stubs_in'
	 4: from /usr/share/rubygems/rubygems/specification.rb:768:in `select'
	 3: from /usr/share/rubygems/rubygems/stub_specification.rb:208:in `valid?'
	 2: from /usr/share/rubygems/rubygems/stub_specification.rb:118:in `data'
	 1: from /usr/share/rubygems/rubygems/stub_specification.rb:118:in `open'
/usr/share/rubygems/rubygems/stub_specification.rb:118:in `initialize': Permission denied @ rb_sysopen - /usr/local/share/gems/specifications/bundler-2.0.1.gemspec (Errno::EACCES)



what can be wrong here?

**Comment by vodolaz095** [comment]
it seems like it reinstalls module when i try to exec it from command line

**Comment by azumakuniyuki** [comment]
@vodolaz095 Would you try to use `STDIN` instead of `<STDIN>` like the following ?

```
$ ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin16]

$ ruby -rsisimai -e 'print Sisimai.version'
4.25.0

$ cat path/to/email | ruby -rsisimai -e 'print Sisimai.dump(STDIN)' 
```
