### ISSUE TITLE
the message should be identified as "user unknown"

### ISSUE THREAD

**Issue by joaoscotto** [sisimai/rb-Sisimai#91]
The message status code is `550 5.1.10 ` however, the actual reason for bounce is being
described in the body of the message.

```
Your message to [redacted]@[redacted].com.br couldn't be delivered.

[redacted] wasn't found at [redacted].com.br.

bounces+bZYxeGz9O4oj...     Office 365     [redacted]
Action Required         Recipient       Unknown To address         


How to Fix It

[some instructions to users]

________________________________________

More Info for Email Admins
Status code: 550 5.1.10 

This error occurs because the sender sent a message to an email address hosted
by Office 365 but the address is incorrect or doesn't exist at the destination
domain. The error is reported by the recipient domain's email server, but most
often it must be fixed by the person who sent the message. 

[some instructions to admins]

Original Message Details
Created Date:    10/31/2017 6:31:48 PM
Sender Address:    bounces+bZYxeGz9O4ojVlpPyb3lNd1pma2v5XPW-=[redacted]=[redacted].com.br@[redacted].com

Recipient Address:    [redacted]@[redacted].com.br

Subject:    [redacted]


Error Details
Reported error:    550 5.1.10 RESOLVER.ADR.RecipientNotFound; Recipien= [redacted]@[redacted].com.br not found by SMTP address lookup 
DSN generated by:    FR1PR80MB0423.lamprd80.prod.outlook.com 


Message Hops

[list of message hops outside and inside outlook.com]
```

I'm not putting the original message because it's very hard to remove sensitive informations, but I can send in private channel if necessary.

Thanks!

**Comment by azumakuniyuki** [comment]
Thanks for the report. But the original message including all the headers is required for fixing this issue. Then, would you check a bounce message at https://raw.githubusercontent.com/AntonyMN/journal/838c50395f91838bc5f02f2c101cac82f481ee7d/mail/remmaword.org/admin/new/1476799163.M862273P14121.junior.vivawebhost.com%2CS%3D62411%2CW%3D63479 ?

If the format of the message above is the same format with the message you have, we'll try to fix this issue using the bounce mail.

Thanks :-)

**Comment by joaoscotto** [comment]
hi @azumakuniyuki 

yes! that bounce message has the same format that my message.

thanks!

**Comment by azumakuniyuki** [comment]
@joaoscotto Thanks for the reply. Then, I have two questions about this issue.

1. What `reason` is the parsed result of the bounce message you have ?
2. Does the value of `rhost` end with `.prod.outlook.com` ?

Thanks.

**Comment by joaoscotto** [comment]
hi @azumakuniyuki 

>What reason is the parsed result of the bounce message you have ?

it's `notaccept`

>Does the value of rhost end with .prod.outlook.com ?

yes

**Comment by azumakuniyuki** [comment]
@joaoscotto Hello, I've merged Pull-Request #94 (Large scale improvement of error message patterns) and released v4.22.2p3 today. The pull-request may resolve this issue, would you try to parse using v4.22.2p3 ?

Thanks.

**Comment by joaoscotto** [comment]
Hi @azumakuniyuki 

that `v4.22.2p3` version did not solve. I ran the parse with the `v4.22.2p3 ` version and the result was `filtered`.

thanks

**Comment by azumakuniyuki** [comment]
Hello @joaoscotto , Thanks for trying v4.22.2p3. I've improved `Sisimai::Rhost::ExchangeOnline` class to resolve this issue. Commit 05b0e44 may be able to fix this issue. Would you try to current `master` branch ?

Thanks.

**Comment by joaoscotto** [comment]
hi @azumakuniyuki 

I tried it and it works fine! Thank you!
