### ISSUE TITLE
Parse sendgrid events json not work with `ActiveSupport::HashWithIndifferentAccess`

### ISSUE THREAD

**Issue by subuta** [sisimai/rb-Sisimai#92]
I had setup SendGrid webhook to post to my Rails app.

And when I got sendgrid json data from `ActionController::Parameters`, `params['_json']` become `ActiveSupport::HashWithIndifferentAccess` instance and passing it to Sisimai.make will returns `nil` . (looks like no events json parsed.)

### Not works...

```ruby
json = params['_json'].map {|j| j.to_unsafe_hash}
#      |                          |                        
#      |                          | -> ActiveSupport::HashWithIndifferentAccess
#      |
#      | -> Array<ActionController::Parameters> ※from SendGrid webhook
#
Sisimai.make(json, input: 'json')
# -> nil
```

As a workaround I had to do following.

### Works!

```ruby
json = params['_json'].map {|j| j.to_unsafe_hash.to_hash}
#      |                          |              | -> Hash
#      |                          | -> ActiveSupport::HashWithIndifferentAccess
#      |
#      | -> Array<ActionController::Parameters> ※from SendGrid webhook
#
Sisimai.make(json, input: 'json')
# -> Array<Sisimai::Data>        
```

Maybe it's not `rb-sisimai`'s fault, but it would be nice to have it documented in somewhere(perhaps at wiki) I think :)

### Versions(from Gemfile.lock)

```
rails (5.1.4)
      actioncable (= 5.1.4)
      actionmailer (= 5.1.4)
      actionpack (= 5.1.4)
      actionview (= 5.1.4)
      activejob (= 5.1.4)
      activemodel (= 5.1.4)
      activerecord (= 5.1.4)
      activesupport (= 5.1.4)
      bundler (>= 1.3.0)
      railties (= 5.1.4)
      sprockets-rails (>= 2.0.0)
...
sisimai (4.22.2)
      oj (~> 3.0.0, >= 3.0.0)
```

**Comment by subuta** [comment]
This line looks suspicious for me

https://github.com/sisimai/rb-Sisimai/blob/634b5587ffd7246e3ec9608b13f13a3f1b607b2c/lib/sisimai.rb#L81

from this `json = params['_json'].map {|j| j.to_unsafe_hash}` json
`e.class.to_s` becomes `ActiveSupport::HashWithIndifferentAccess`
even though `ActiveSupport::HashWithIndifferentAccess` extends `Hash` class 😞 

http://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html

**Comment by azumakuniyuki** [comment]
@subuta Thanks for the report ! Sure, this issue and solutions should be documented at Wiki or README.

`Sisimai.make` method expect only raw format of SendGrid Event Webhook object like https://sendgrid.com/docs/API_Reference/Webhooks/event.html#-Bounce .

And then, the line 81 on sisimai.rb might not be required... `rake spec` has successfully completed after removing the line.

**Comment by azumakuniyuki** [comment]
@subuta If this issue will be resolved when the line 81 on `sisimai.rb` is removed, would you create a Pull-Request to resolve this issue ? Because I've no environment to get a object of ActiveSupport...

**Comment by subuta** [comment]
@azumakuniyuki Thanks for quick reply.
OK, I will try your fix(remove line 81) for `sisimai.rb` and create PR later :)
